version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: leaderboard_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=dev
      - MONGO_INITDB_DATABASE=leaderboard
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
volumes:
  mongodata: